-- Inventário somente de estrutura e contagens. Não exporta senhas, sessões ou conteúdo dos usuários.
BEGIN READ ONLY;
SELECT jsonb_build_object(
 'consultado_em',current_timestamp,
 'versao',version(),
 'database',current_database(),
 'schemas',(SELECT jsonb_agg(jsonb_build_object('nome',nspname,'owner',pg_get_userbyid(nspowner),'acl',nspacl::text) ORDER BY nspname) FROM pg_namespace WHERE nspname NOT LIKE 'pg_%' AND nspname <> 'information_schema'),
 'extensoes',(SELECT jsonb_agg(jsonb_build_object('nome',e.extname,'versao',e.extversion,'schema',n.nspname) ORDER BY e.extname) FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace),
 'tabelas',(SELECT jsonb_agg(jsonb_build_object(
   'schema',n.nspname,'nome',c.relname,'tipo',c.relkind,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,
   'comentario',obj_description(c.oid,'pg_class'),
   'colunas',(SELECT jsonb_agg(jsonb_build_object('nome',a.attname,'tipo',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),'identity',a.attidentity,'generated',a.attgenerated,'comentario',col_description(c.oid,a.attnum)) ORDER BY a.attnum) FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),
   'constraints',(SELECT jsonb_agg(jsonb_build_object('nome',conname,'tipo',contype,'definicao',pg_get_constraintdef(oid,true)) ORDER BY conname) FROM pg_constraint WHERE conrelid=c.oid),
   'indices',(SELECT jsonb_agg(jsonb_build_object('nome',ic.relname,'definicao',pg_get_indexdef(i.indexrelid),'constraint',EXISTS(SELECT 1 FROM pg_constraint con WHERE con.conindid=i.indexrelid)) ORDER BY ic.relname) FROM pg_index i JOIN pg_class ic ON ic.oid=i.indexrelid WHERE i.indrelid=c.oid),
   'triggers',(SELECT jsonb_agg(jsonb_build_object('nome',tgname,'definicao',pg_get_triggerdef(oid,true),'enabled',tgenabled) ORDER BY tgname) FROM pg_trigger WHERE tgrelid=c.oid AND NOT tgisinternal),
   'policies',(SELECT jsonb_agg(jsonb_build_object('nome',policyname,'permissive',permissive,'roles',roles,'command',cmd,'using',qual,'check',with_check) ORDER BY policyname) FROM pg_policies WHERE schemaname=n.nspname AND tablename=c.relname)
 ) ORDER BY n.nspname,c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind IN ('r','p') AND n.nspname NOT LIKE 'pg_%' AND n.nspname <> 'information_schema'),
 'views',(SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'nome',c.relname,'definicao',pg_get_viewdef(c.oid,true)) ORDER BY n.nspname,c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind IN ('v','m') AND n.nspname IN ('public','private')),
 'enums',(SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'nome',t.typname,'valores',(SELECT jsonb_agg(enumlabel ORDER BY enumsortorder) FROM pg_enum WHERE enumtypid=t.oid)) ORDER BY n.nspname,t.typname) FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE t.typtype='e' AND n.nspname IN ('public','private')),
 'sequencias',(SELECT jsonb_agg(jsonb_build_object('schema',schemaname,'nome',sequencename,'tipo',data_type,'inicio',start_value,'min',min_value,'max',max_value,'incremento',increment_by,'ciclo',cycle,'cache',cache_size) ORDER BY schemaname,sequencename) FROM pg_sequences WHERE schemaname IN ('public','private')),
 'funcoes',(SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'nome',p.proname,'assinatura',pg_get_function_identity_arguments(p.oid),'argumentos',pg_get_function_arguments(p.oid),'retorno',pg_get_function_result(p.oid),'security_definer',p.prosecdef,'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'config',p.proconfig,'definicao',pg_get_functiondef(p.oid)) ORDER BY n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('public','private') AND p.prokind='f' AND NOT EXISTS(SELECT 1 FROM pg_depend d WHERE d.classid='pg_proc'::regclass AND d.objid=p.oid AND d.deptype='e')),
 'default_acl',(SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'role',pg_get_userbyid(d.defaclrole),'tipo',d.defaclobjtype,'acl',d.defaclacl::text)) FROM pg_default_acl d LEFT JOIN pg_namespace n ON n.oid=d.defaclnamespace),
 'migrations',(SELECT jsonb_agg(jsonb_build_object('versao',version,'nome',name) ORDER BY version) FROM supabase_migrations.schema_migrations),
 'buckets',(SELECT jsonb_agg(jsonb_build_object('id',id,'nome',name,'publico',public,'limite_bytes',file_size_limit,'tipos',allowed_mime_types,'objetos',(SELECT count(*) FROM storage.objects o WHERE o.bucket_id=b.id),'bytes',(SELECT sum((metadata->>'size')::bigint) FROM storage.objects o WHERE o.bucket_id=b.id)) ORDER BY id) FROM storage.buckets b),
 'contagens',jsonb_build_object('usuarios',(SELECT count(*) FROM public.usuarios),'funcionarios',(SELECT count(*) FROM public.funcionarios),'veiculos',(SELECT count(*) FROM public.veiculos),'contratos',(SELECT count(*) FROM public.contratos),'tipos_manutencao',(SELECT count(*) FROM public.tipos_manutencao),'registros_frota',(SELECT count(*) FROM public.registros_frota),'registro_equipes',(SELECT count(*) FROM public.registro_equipes),'manutencoes',(SELECT count(*) FROM public.manutencoes),'veiculo_documentos',(SELECT count(*) FROM public.veiculo_documentos),'documentos_vinculados',(SELECT count(*) FROM public.veiculo_documentos WHERE veiculo_id IS NOT NULL),'veiculos_com_crlv',(SELECT count(DISTINCT veiculo_id) FROM public.veiculo_documentos))
) AS inventario;
ROLLBACK;
